/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CoordinatorId = IDL.Text;
export const Coordinator = IDL.Record({
  'id' : CoordinatorId,
  'principal' : IDL.Principal,
  'grade' : IDL.Text,
  'passwordHash' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const VolunteerId = IDL.Text;
export const EventId = IDL.Text;
export const Time = IDL.Int;
export const ReportDocumentHash = IDL.Vec(IDL.Nat8);
export const ReportImageBlob = IDL.Vec(IDL.Nat8);
export const VolunteerReport = IDL.Record({
  'eventId' : EventId,
  'submissionTimestamp' : Time,
  'reportText' : IDL.Text,
  'grade' : IDL.Opt(IDL.Text),
  'secureHash' : ReportDocumentHash,
  'images' : IDL.Vec(ReportImageBlob),
});
export const AvatarBlob = IDL.Vec(IDL.Nat8);
export const Volunteer = IDL.Record({
  'id' : VolunteerId,
  'principal' : IDL.Principal,
  'matricule' : IDL.Text,
  'reports' : IDL.Vec(VolunteerReport),
  'passwordHash' : IDL.Text,
  'registrationDate' : IDL.Text,
  'lastName' : IDL.Text,
  'avatar' : IDL.Opt(AvatarBlob),
  'firstName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'admin' : IDL.Null,
    'coordinator' : IDL.Null,
    'volunteer' : IDL.Null,
  }),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoordinator' : IDL.Func([Coordinator], [], []),
  'addVolunteer' : IDL.Func([Volunteer], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCoordinator' : IDL.Func([CoordinatorId], [], []),
  'deleteVolunteer' : IDL.Func([VolunteerId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoordinator' : IDL.Func([CoordinatorId], [Coordinator], ['query']),
  'getCoordinators' : IDL.Func([], [IDL.Vec(Coordinator)], ['query']),
  'getMyCoordinatorProfile' : IDL.Func([], [IDL.Opt(Coordinator)], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(VolunteerReport)], ['query']),
  'getMyVolunteerProfile' : IDL.Func([], [IDL.Opt(Volunteer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteer' : IDL.Func([VolunteerId], [Volunteer], ['query']),
  'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'gradeVolunteerReport' : IDL.Func(
      [CoordinatorId, VolunteerId, EventId, IDL.Text],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitVolunteerReport' : IDL.Func(
      [
        VolunteerId,
        EventId,
        IDL.Text,
        IDL.Vec(ReportImageBlob),
        ReportDocumentHash,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CoordinatorId = IDL.Text;
  const Coordinator = IDL.Record({
    'id' : CoordinatorId,
    'principal' : IDL.Principal,
    'grade' : IDL.Text,
    'passwordHash' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const VolunteerId = IDL.Text;
  const EventId = IDL.Text;
  const Time = IDL.Int;
  const ReportDocumentHash = IDL.Vec(IDL.Nat8);
  const ReportImageBlob = IDL.Vec(IDL.Nat8);
  const VolunteerReport = IDL.Record({
    'eventId' : EventId,
    'submissionTimestamp' : Time,
    'reportText' : IDL.Text,
    'grade' : IDL.Opt(IDL.Text),
    'secureHash' : ReportDocumentHash,
    'images' : IDL.Vec(ReportImageBlob),
  });
  const AvatarBlob = IDL.Vec(IDL.Nat8);
  const Volunteer = IDL.Record({
    'id' : VolunteerId,
    'principal' : IDL.Principal,
    'matricule' : IDL.Text,
    'reports' : IDL.Vec(VolunteerReport),
    'passwordHash' : IDL.Text,
    'registrationDate' : IDL.Text,
    'lastName' : IDL.Text,
    'avatar' : IDL.Opt(AvatarBlob),
    'firstName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'admin' : IDL.Null,
      'coordinator' : IDL.Null,
      'volunteer' : IDL.Null,
    }),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoordinator' : IDL.Func([Coordinator], [], []),
    'addVolunteer' : IDL.Func([Volunteer], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCoordinator' : IDL.Func([CoordinatorId], [], []),
    'deleteVolunteer' : IDL.Func([VolunteerId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoordinator' : IDL.Func([CoordinatorId], [Coordinator], ['query']),
    'getCoordinators' : IDL.Func([], [IDL.Vec(Coordinator)], ['query']),
    'getMyCoordinatorProfile' : IDL.Func([], [IDL.Opt(Coordinator)], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(VolunteerReport)], ['query']),
    'getMyVolunteerProfile' : IDL.Func([], [IDL.Opt(Volunteer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteer' : IDL.Func([VolunteerId], [Volunteer], ['query']),
    'getVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'gradeVolunteerReport' : IDL.Func(
        [CoordinatorId, VolunteerId, EventId, IDL.Text],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitVolunteerReport' : IDL.Func(
        [
          VolunteerId,
          EventId,
          IDL.Text,
          IDL.Vec(ReportImageBlob),
          ReportDocumentHash,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };