/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvatarBlob = Uint8Array;
export interface Coordinator {
  'id' : CoordinatorId,
  'principal' : Principal,
  'grade' : string,
  'passwordHash' : string,
  'lastName' : string,
  'firstName' : string,
}
export type CoordinatorId = string;
export type EventId = string;
export type ReportDocumentHash = Uint8Array;
export type ReportImageBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'userType' : { 'admin' : null } |
    { 'coordinator' : null } |
    { 'volunteer' : null },
  'userId' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : VolunteerId,
  'principal' : Principal,
  'matricule' : string,
  'reports' : Array<VolunteerReport>,
  'passwordHash' : string,
  'registrationDate' : string,
  'lastName' : string,
  'avatar' : [] | [AvatarBlob],
  'firstName' : string,
}
export type VolunteerId = string;
export interface VolunteerReport {
  'eventId' : EventId,
  'submissionTimestamp' : Time,
  'reportText' : string,
  'grade' : [] | [string],
  'secureHash' : ReportDocumentHash,
  'images' : Array<ReportImageBlob>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoordinator' : ActorMethod<[Coordinator], undefined>,
  'addVolunteer' : ActorMethod<[Volunteer], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCoordinator' : ActorMethod<[CoordinatorId], undefined>,
  'deleteVolunteer' : ActorMethod<[VolunteerId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoordinator' : ActorMethod<[CoordinatorId], Coordinator>,
  'getCoordinators' : ActorMethod<[], Array<Coordinator>>,
  'getMyCoordinatorProfile' : ActorMethod<[], [] | [Coordinator]>,
  'getMyReports' : ActorMethod<[], Array<VolunteerReport>>,
  'getMyVolunteerProfile' : ActorMethod<[], [] | [Volunteer]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteer' : ActorMethod<[VolunteerId], Volunteer>,
  'getVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'gradeVolunteerReport' : ActorMethod<
    [CoordinatorId, VolunteerId, EventId, string],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitVolunteerReport' : ActorMethod<
    [VolunteerId, EventId, string, Array<ReportImageBlob>, ReportDocumentHash],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];