/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AvatarBlob = Uint8Array;
export type Time = bigint;
export type EventId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type VolunteerId = string;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VolunteerReport {
    eventId: EventId;
    submissionTimestamp: Time;
    reportText: string;
    grade?: string;
    secureHash: ReportDocumentHash;
    images: Array<ReportImageBlob>;
}
export type ReportImageBlob = Uint8Array;
export type ReportDocumentHash = Uint8Array;
export type CoordinatorId = string;
export interface Coordinator {
    id: CoordinatorId;
    principal: Principal;
    grade: string;
    passwordHash: string;
    lastName: string;
    firstName: string;
}
export interface Volunteer {
    id: VolunteerId;
    principal: Principal;
    matricule: string;
    reports: Array<VolunteerReport>;
    passwordHash: string;
    registrationDate: string;
    lastName: string;
    avatar?: AvatarBlob;
    firstName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    userType: Variant_admin_coordinator_volunteer;
    userId: string;
    name: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_admin_coordinator_volunteer {
    admin = "admin",
    coordinator = "coordinator",
    volunteer = "volunteer"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoordinator(coordinator: Coordinator): Promise<void>;
    addVolunteer(volunteer: Volunteer): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCoordinator(id: CoordinatorId): Promise<void>;
    deleteVolunteer(id: VolunteerId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoordinator(id: CoordinatorId): Promise<Coordinator>;
    getCoordinators(): Promise<Array<Coordinator>>;
    getMyCoordinatorProfile(): Promise<Coordinator | null>;
    getMyReports(): Promise<Array<VolunteerReport>>;
    getMyVolunteerProfile(): Promise<Volunteer | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVolunteer(id: VolunteerId): Promise<Volunteer>;
    getVolunteers(): Promise<Array<Volunteer>>;
    gradeVolunteerReport(coordinatorId: CoordinatorId, volunteerId: VolunteerId, eventId: EventId, grade: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitVolunteerReport(volunteerId: VolunteerId, eventId: EventId, reportText: string, images: Array<ReportImageBlob>, secureHash: ReportDocumentHash): Promise<void>;
}
import type { AvatarBlob as _AvatarBlob, Coordinator as _Coordinator, EventId as _EventId, ReportDocumentHash as _ReportDocumentHash, ReportImageBlob as _ReportImageBlob, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Volunteer as _Volunteer, VolunteerId as _VolunteerId, VolunteerReport as _VolunteerReport, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoordinator(arg0: Coordinator): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoordinator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoordinator(arg0);
            return result;
        }
    }
    async addVolunteer(arg0: Volunteer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVolunteer(to_candid_Volunteer_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVolunteer(to_candid_Volunteer_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCoordinator(arg0: CoordinatorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoordinator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoordinator(arg0);
            return result;
        }
    }
    async deleteVolunteer(arg0: VolunteerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVolunteer(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoordinator(arg0: CoordinatorId): Promise<Coordinator> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoordinator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoordinator(arg0);
            return result;
        }
    }
    async getCoordinators(): Promise<Array<Coordinator>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoordinators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoordinators();
            return result;
        }
    }
    async getMyCoordinatorProfile(): Promise<Coordinator | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCoordinatorProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCoordinatorProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReports(): Promise<Array<VolunteerReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReports();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReports();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVolunteerProfile(): Promise<Volunteer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVolunteerProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVolunteerProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteer(arg0: VolunteerId): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteer(arg0);
                return from_candid_Volunteer_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteer(arg0);
            return from_candid_Volunteer_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteers();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteers();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeVolunteerReport(arg0: CoordinatorId, arg1: VolunteerId, arg2: EventId, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeVolunteerReport(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeVolunteerReport(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitVolunteerReport(arg0: VolunteerId, arg1: EventId, arg2: string, arg3: Array<ReportImageBlob>, arg4: ReportDocumentHash): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVolunteerReport(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVolunteerReport(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VolunteerReport_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VolunteerReport): VolunteerReport {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Volunteer_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Volunteer): Volunteer {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinator]): Coordinator | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Volunteer]): Volunteer | null {
    return value.length === 0 ? null : from_candid_Volunteer_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvatarBlob]): AvatarBlob | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        admin: null;
    } | {
        coordinator: null;
    } | {
        volunteer: null;
    };
    userId: string;
    name: string;
    email: string;
}): {
    userType: Variant_admin_coordinator_volunteer;
    userId: string;
    name: string;
    email: string;
} {
    return {
        userType: from_candid_variant_n18(_uploadFile, _downloadFile, value.userType),
        userId: value.userId,
        name: value.name,
        email: value.email
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: _EventId;
    submissionTimestamp: _Time;
    reportText: string;
    grade: [] | [string];
    secureHash: _ReportDocumentHash;
    images: Array<_ReportImageBlob>;
}): {
    eventId: EventId;
    submissionTimestamp: Time;
    reportText: string;
    grade?: string;
    secureHash: ReportDocumentHash;
    images: Array<ReportImageBlob>;
} {
    return {
        eventId: value.eventId,
        submissionTimestamp: value.submissionTimestamp,
        reportText: value.reportText,
        grade: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.grade)),
        secureHash: value.secureHash,
        images: value.images
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VolunteerId;
    principal: Principal;
    matricule: string;
    reports: Array<_VolunteerReport>;
    passwordHash: string;
    registrationDate: string;
    lastName: string;
    avatar: [] | [_AvatarBlob];
    firstName: string;
}): {
    id: VolunteerId;
    principal: Principal;
    matricule: string;
    reports: Array<VolunteerReport>;
    passwordHash: string;
    registrationDate: string;
    lastName: string;
    avatar?: AvatarBlob;
    firstName: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        matricule: value.matricule,
        reports: from_candid_vec_n22(_uploadFile, _downloadFile, value.reports),
        passwordHash: value.passwordHash,
        registrationDate: value.registrationDate,
        lastName: value.lastName,
        avatar: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.avatar)),
        firstName: value.firstName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    coordinator: null;
} | {
    volunteer: null;
}): Variant_admin_coordinator_volunteer {
    return "admin" in value ? Variant_admin_coordinator_volunteer.admin : "coordinator" in value ? Variant_admin_coordinator_volunteer.coordinator : "volunteer" in value ? Variant_admin_coordinator_volunteer.volunteer : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VolunteerReport>): Array<VolunteerReport> {
    return value.map((x)=>from_candid_VolunteerReport_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Volunteer>): Array<Volunteer> {
    return value.map((x)=>from_candid_Volunteer_n27(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_VolunteerReport_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VolunteerReport): _VolunteerReport {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Volunteer_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Volunteer): _Volunteer {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: EventId;
    submissionTimestamp: Time;
    reportText: string;
    grade?: string;
    secureHash: ReportDocumentHash;
    images: Array<ReportImageBlob>;
}): {
    eventId: _EventId;
    submissionTimestamp: _Time;
    reportText: string;
    grade: [] | [string];
    secureHash: _ReportDocumentHash;
    images: Array<_ReportImageBlob>;
} {
    return {
        eventId: value.eventId,
        submissionTimestamp: value.submissionTimestamp,
        reportText: value.reportText,
        grade: value.grade ? candid_some(value.grade) : candid_none(),
        secureHash: value.secureHash,
        images: value.images
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: Variant_admin_coordinator_volunteer;
    userId: string;
    name: string;
    email: string;
}): {
    userType: {
        admin: null;
    } | {
        coordinator: null;
    } | {
        volunteer: null;
    };
    userId: string;
    name: string;
    email: string;
} {
    return {
        userType: to_candid_variant_n33(_uploadFile, _downloadFile, value.userType),
        userId: value.userId,
        name: value.name,
        email: value.email
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VolunteerId;
    principal: Principal;
    matricule: string;
    reports: Array<VolunteerReport>;
    passwordHash: string;
    registrationDate: string;
    lastName: string;
    avatar?: AvatarBlob;
    firstName: string;
}): {
    id: _VolunteerId;
    principal: Principal;
    matricule: string;
    reports: Array<_VolunteerReport>;
    passwordHash: string;
    registrationDate: string;
    lastName: string;
    avatar: [] | [_AvatarBlob];
    firstName: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        matricule: value.matricule,
        reports: to_candid_vec_n10(_uploadFile, _downloadFile, value.reports),
        passwordHash: value.passwordHash,
        registrationDate: value.registrationDate,
        lastName: value.lastName,
        avatar: value.avatar ? candid_some(value.avatar) : candid_none(),
        firstName: value.firstName
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_admin_coordinator_volunteer): {
    admin: null;
} | {
    coordinator: null;
} | {
    volunteer: null;
} {
    return value == Variant_admin_coordinator_volunteer.admin ? {
        admin: null
    } : value == Variant_admin_coordinator_volunteer.coordinator ? {
        coordinator: null
    } : value == Variant_admin_coordinator_volunteer.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VolunteerReport>): Array<_VolunteerReport> {
    return value.map((x)=>to_candid_VolunteerReport_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
